### ISSUE TITLE
Refactor qmlbind_interface, qmlbind_exporter, qmlbind_interface_handlers and qmlbind_backref

### ISSUE THREAD

**Issue by florianjacob** [seanchas116/libqmlbind#15]
As discussed in https://github.com/seanchas116/libqmlbind/pull/9#issuecomment-200306353, `qmlbind_interface` and `qmlbind_interface_handlers` can probably merged into one thing from the perspective of libqmlbind's API. The exporter could then directly take the `interface_handlers` and be renamed into something like `metaobject_builder`, to make its intent more obvious.

**Comment by florianjacob** [comment]
I'm also not too hapy with the naming of `qmlbind_backref`, and the reference to “wrappers“ in that context. Those terms make sense from an internal `libqmlbind` view, but I found it hard to understand if you only try to figure out the API.

Also, `qmlbind_backref` is mainly used for pointers to QObject-equivalents, but also as reference to class objects. If the `classRef` argument is kept, it should probably get its own type to differentiate them externally, even if they're the same implementation-wise. We could then rename `qmlbind_backref` to something like `qmlbind_qobject` to make it easier to understand.

**Comment by seanchas116** [comment]
I also think `qmlbind_backref` is confusing and want to refactor it :confused: 
`qmlbind_qobject`would be a good naming but it might be confusing with `qmlbind_application` or `qmlbind_engine` which are internally QObject. I prefer using name simply `qmlbind_wrapped` for objects that are wrapped into QObjects and `qmlbind_class` for class data.

**Comment by florianjacob** [comment]
You're right, we need to distinguish, as the backref is really not a pointer to just any QObject. I'd 
prefer not to call it `qmlbind_wrapped`, because this could also be understood as as the wrapper together with the wrapped thing inside or being already wrapped, which is e.g. not the case here:
```C
qmlbind_value qmlbind_engine_new_wrapper(qmlbind_wrapped *objRef);
```

What about calling it *just* `qmlbind_object`, matching to `qmlbind_class`, and defining them as “client code's object” and “client code's class“ somehow along the lines of this:

```C
/*!
 * \brief an opaque struct used to transfer objects exposed to the metaobject system between libqmlbind and its user.
 *
 * In `qmlbind_interface_handlers`' `new_object()`, you need to return a `qmlbind_object` pointer, which is then given
 * back to you as `objRef` parameter in `call_method()`, `get_property()` and `set_property()`.
 * With the `qmlbind_interface_handlers`, `qmlbind_object`s can be created, used and deleted from QML.
 *
 * A `qmlbind_object` therefore is the rough equivalent of an instance of a
 * [QObject](http://doc.qt.io/qt-5/qobject.html#QObject) in code using libqmlbind.
 *
 * See `qmlbind_engine_new_wrapper()` to create new `qmlbind_value` wrappers for a `qmlbind_object`, and
 * `qmlbind_value_get_qmlbind_object()` to get the wrapped `qmlbind_object` back.
 */
typedef struct qmlbind_object {} qmlbind_object;

/*!
 * \brief an opaque struct used to transfer class objects of classes exposed to the metaobject system between libqmlbind
 * and its user.
 *
 * This is intended to be used in languages that have the concept of a class object with which you can generically
 * construct new objects. With that, you can implement generic `qmlbind_interface_handlers` for all classes. In other
 * languages, you can ignore it and implement multiple `qmlbind_interface_handlers`.
 *
 * A `qmlbind_class` therefore is the rough equivalent of a
 * [QObject](http://doc.qt.io/qt-5/qobject.html#QObject) class in code using libqmlbind.
 *
 * In `qmlbind_exporter_new()`, a `qmlbind_class` pointer can be provided which is forwarded to
 * `qmlbind_interface_handlers`' `new_object()` for that purpose. You could use it to transfer an arbitrary object,
 * though.
 */
typedef struct qmlbind_class {} qmlbind_class;
```

**Comment by seanchas116** [comment]
One thing I would concern about is `qmlbind_object` is confusing with JavaScript objects.
How about more explicit naming `qmlbind_client_object` and `qmlbind_client_class` ?

**Comment by florianjacob** [comment]
You're right, confusion with JavaScript objects would be imminent.

I really like the explicit `client` prefix idea because it is explicit about the fact that with these two structs, it's not the client who is accessing an opaque libqmlbind struct, but the other way around.

**Comment by florianjacob** [comment]
I'll try out the renaming & split and see how well it works out. :smile: 

As this will be the first in a number of breaking changes, did you thought about having a release in beforehand, e.g. tagging the current state as v0.1.0 or something?

**Comment by seanchas116** [comment]
I just tagged version [v0.1.0](https://github.com/seanchas116/libqmlbind/releases/tag/v0.1.0).

**Comment by rainbyte** [comment]
While implementing fizzbuzz example I realized that it is not clear (at least to me) how to use qmlbind_backref's, or even what they really are, when reading the docs.

qmlbind_exporter_new docs says that qmlbind_backref parameter could be omitted by passing a nullptr if it is not needed... But it is not explained when it is needed or how to create it.

As C doesn't have OOP-style classes, I'm trying to use an ADT oriented approach. As I understand, qmlbind_interface_handlers callbacks should be written so the ADT is handled by them. 

The ADT is received via an qmlbind_backref parameter (?). Maybe I'm missing something?

(sorry if not clear, english is not my native language) :/

**Comment by florianjacob** [comment]
I think I figured out a nice way to solve the problems. I found no way to incrementally change the architecture to it, though, so you'll have to read through quite a number of changes in an hour or two when it's ready to be uploaded.

@rainbyte Did you find this part of `qmlbind_backref`'s documentation?:
```
…
In qmlbind_exporter_new(), it is used as classRef which is forwarded qmlbind_interface_handlers' new_object(). In this case, it's a pointer to an arbitrary object in the calling code, intended to be used for a generic class object, which you can use to create new objRefs returned by new_object(). 
```
I thought it would be more fitting to include it there to explain the different roles a `qmlbind_backref` can have. Essentially, whatever you'll pass to `qmlbind_exporter_new()` as `classRef` will be given back to you on your implementation of `qmlbind_interface_handlers`' `new_object()` as `classRef`. libqmlbind does not modify it and does not care, that's why you could also pass a nullptr if you don't need it.

Essentially, you have two options on how to implement this in the client code:
 * Implement specific `qmlbind_interface_handlers`, one for each specific type of object / struct / thing exposed to the metaobject system which can only create objects of that type. In that case, pass a nullptr to `qmlbind_exporter` and ignore the `classRef` argument when implementing `new_object`.
 * Implement a singe generic `qmlbind_interface_handlers` for all types. In a language where you can generically refer to classes as objects (called class objects or metaclasses) and then do something like (written in pseudo-python)
```python
class Car {
…
}
type klass = Car;
def new_object(klass) {
    return klass.__init__();
}
```
this is the easier choice, because you can then pass `klass` as `classRef` and use it for generic object creation in `new_object`.

In the case of C, probably the first option is best. Don't hesitate to upload unfinished code and let me take a look on it, you can always force-push and rebase. :wink: 

> (sorry if not clear, english is not my native language) :/

Don't worry, it's for neither of us. :smile: :de: :jp: :earth_africa:

**Comment by florianjacob** [comment]
I hope the type split between the `qmlbind_backref` variants will help the understandig of what's going on there. :innocent:

**Comment by rainbyte** [comment]
I did not see that piece of documentation about qmlbind_backref (maybe documentation about it is scarse?), now it makes sense to me a bit more... 

I was looking for a function which would wrap my ADT inside the qmlbind_backref, but that is done automatically by qmlbind_exporter_new(). 

I'll try later after returning from work :)

**Comment by rainbyte** [comment]
Another detail: documentation mentions about properties being read and write... Is it not posible to have inmutable (read only) properties?

**Comment by florianjacob** [comment]
> I did not see that piece of documentation about qmlbind_backref (maybe documentation about it is scarse?), now it makes sense to me a bit more...
I'll try to make it more connected in this branch. :smile: 

> Another detail: documentation mentions about properties being read and write... Is it not posible to have inmutable (read only) properties?
Yes, you're right, thanks for pointing out this is not said explicit enough. Just updated the documentation to make it more clear, see: 39da1a1449992192939f929ac6c01a517238299.

**Comment by florianjacob** [comment]
I'm quite happy with the general results now, next is to find out why https://travis-ci.org/seanchas116/libqmlbind/jobs/121011730 is failing now…

Code is ready to be reviewed now. I know this turned out to be quite radical, but from my studies of the internal dependencies and lifetimes, I'm quite sure `Backref` and `Interface` were actually not needed anymore in the current code.

@seanchas116 I just found out how to structure the documentation into modules which makes it possible to combine related structs & functions on one page. I think this is a big improvement. :smile: 

`qmlbind_interface_handlers`, `qmlbind_client_object` and `qmlbind_client_class` went into one module as they're strongly related and the three only types implemented by the client. I'm thinking about a rename of `qmlbind_interface_handlers` now to fit the scheme. @seanchas116 thoughts? Maybe `qmlbind_client_interface`? But I'm not too happy with that.

Also, the `qmlbind_engine_new_wrapper(qmlbind_client_object*)` function caught my attention. I found no usage in ruby-qml, but I interpreted its intended useage as to create values that can be used for `qmlbind_value_set_property()`, as reflected in the documentation. The problems I see with it are with the `qmlbind_signal_emitter` inside `qmlbind_client_object*`:

a) where does it come from if the client created the object?

b) how is it associated with the new `Wrapper` QObject created in `qmlbind_engine_new_wrapper()`?

Seems to me like signals are actually broken in that case. I think this can be solved by passing the `qmlbind_metaclass` instead and then letting libqmlbind take care of the object creation and `qmlbind_signal_emitter` setup, as it's done when creating objects from registered metaclasses.

**Comment by florianjacob** [comment]
Fixed the failing test. \o/ It was a signal name vs. signal signature problem once again.

**Comment by rainbyte** [comment]
@florianjacob, what about renaming qmlbin_interface_handlers to qmlbind_client_callbacks?

**Comment by seanchas116** [comment]
> I interpreted its intended useage as to create values that can be used for qmlbind_value_set_property()

Yes, I intended `qmlbind_engine_new_wrapper` to be used when users want to create wrapper without registering type in `qmlbind_register_type`, such as setting client object directly in `qmlbind_value_set_property`.

`qmlbind_signal_emitter` just wraps an `Wrapper` object and emits signals by calling `QMetaObject::activate`, so we can create a constructor like `qmlbind_signal_emitter_new(const qmlbind_value *wrapper)`  so users can use it along with `qmlbind_engine_new_wrapper`.

**Comment by seanchas116** [comment]
> what about renaming qmlbin_interface_handlers to qmlbind_client_callbacks?

I like `qmlbind_client_callbacks` idea too. I think it clearly means it is a set of callback functions (not a opaque pointer) and its functions are provided by the client and for client objects/classes.

**Comment by seanchas116** [comment]
I created a separate issue #28 to support read-only properties.

**Comment by florianjacob** [comment]
>  what about renaming qmlbin_interface_handlers to qmlbind_client_callbacks?

@rainbyte I'm in the process of renaming now and `qmlbind_client_callbacks` really looks much better. Thanks!

**Comment by florianjacob** [comment]
> qmlbind_signal_emitter just wraps an Wrapper object and emits signals by calling QMetaObject::activate, so we could create a constructor like qmlbind_signal_emitter_new(const qmlbind_value *wrapper) so users can use it along with qmlbind_engine_new_wrapper.

Yes, I see now that this is more useful than my proposal. I'm implementing this now.

**Comment by florianjacob** [comment]
I now did everything I wanted to achieve here and pushed it to #26. :grin: It is now ready to be reviewed and merged if you don't find something that should change.
