### ISSUE TITLE
Remove Qt private header dependency

### ISSUE THREAD

**Issue by seanchas116** [seanchas116/libqmlbind#19]
Currently libqmlbind depends on Qt private headers:

> This project is using private headers and will therefore be tied to this specific Qt module build version. Running this project against other versions of the Qt modules may crash at any arbitrary point. This is not a bug, but a result of using Qt internals. You have been warned!

To make libqmlbind more portable,  Qt private header dependency should be removed.

**Comment by florianjacob** [comment]
Private headers used:
```
#include <private/qobject_p.h>
#include <private/qmetaobjectbuilder_p.h>
```

The QML C wrapper of qmlrs creates a `QDynamicObject` subclass of `QObject` and does not need private headers: https://github.com/cyndis/qmlrs/tree/master/ext/libqmlrswrapper
But I'm not sure yet whether this actually covers some functionality private headers are currently used for. Now that I understand libqmlbind I'll have a look at that code tomorrow and see how the approaches compare.

**Comment by seanchas116** [comment]
libqmlbind uses private headers just for building custom meta objects dynamically.
Looks like qmlrs builds dynamic meta objects on its own, so it would be possible to bring that code to libqmlbind and remove private header dependency.
