### ISSUE TITLE
Elixir Bindings

### ISSUE THREAD

**Issue by ShalokShalom** [seanchas116/libqmlbind#45]
Hi dude

Can you link us to the specific dynamic API parts in your code?

**Comment by florianjacob** [comment]
I'm guessing you are referring to
> While libqmlbind was designed with dynamic languages like ruby in mind, DOtherSide was designed for static languages like D. (You can use libqmlbind for static languages, too, though, you just won't need some parts of the API).

is that right? This is e.g. about stuff like being able to add a pointer to a class object like in ruby or python when registering a metaclass ( [qmlbind_metaclass_new](https://seanchas116.github.io/libqmlbind/group__metaclass__module.html#ga9dbb515319c62036fe309610a0d8a66d) ) which is then handed to the qmlbind_client_callback's [new_object](https://seanchas116.github.io/libqmlbind/structqmlbind__client__callbacks.html#a998d81dff613775d280e0e27eed70295)

This can be used to write a generic implementation for all client_callbacks, especially new_object, like it's done for ruby-qml here: https://github.com/seanchas116/ruby-qml/blob/8e809d1b1a03b856c4a4da6e221e5f8fcb0c3b9a/ext/qml/meta_class.c#L16

But with static languages where something like a class object does not exist, you would more likely add *different* qmlbind_client_callbacks on each registration, not needing the class object pointer, but probably using your language's feature of generics / templates or macros to create fitting callbacks for each class to register.

Why do you ask?

**Comment by ShalokShalom** [comment]
Elixir, which is a functional and dynamic typed language.

**Comment by florianjacob** [comment]
I'm quite sure there are no libqmlbind C API functions that you don't need to implement depending on whether you're creating bindings for static or dynamic languages.

I'd recommend to just go ahead, wrap every C function for elixir, and then connect those with elixir code to build something on top of that that can be used like things in elixir usually are used, to hide away the fact that under that everything is done as C function calls.

**Comment by ShalokShalom** [comment]
I found that https://github.com/elixirscript/elixirscript/ compiles to Javascript, which means i can use it for QML. Thanks a lot

**Comment by florianjacob** [comment]
👍
